version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    assignees:
      - ozgurakgun
    groups:
      all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "dependencies::rust"

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
    assignees:
      - ozgurakgun
    groups:
      all:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "dependencies::rust"

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    assignees:
      - ozgurakgun
    labels:
      - "dependencies"
      - "dependencies::submodules"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - ozgurakgun
    labels:
      - "dependencies"
      - "dependencies::ci"
