use std::fmt::Display;

use polyquine::Quine;
use serde::{Deserialize, Serialize};
use ustr::Ustr;

/// A reference to an object stored in the [`SymbolTable`].
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Quine)]
#[path_prefix(conjure_cp::ast)]
pub enum Name {
    /// A name given in the input model.
    User(Ustr),
    /// A name generated by Conjure-Oxide.
    Machine(i32),
    /// A name generated as part of a representation.
    Repr(
        Box<(
            // The original variable name
            Name,
            // Name of representation rule
            Ustr,
            // Extra suffix added by the rule
            Ustr,
        )>,
    ),
}

impl Name {
    /// Creates a new `Name::User` from a `&str`.
    pub fn user(name: &str) -> Self {
        Name::User(Ustr::from(name))
    }

    /// Creates a new `Name::Repr`
    pub fn repr(src: Name, rule_name: &str, suffix: &str) -> Self {
        Name::Repr(Box::new((src, Ustr::from(rule_name), Ustr::from(suffix))))
    }
}

impl Default for Name {
    fn default() -> Self {
        Name::User(Ustr::from(""))
    }
}

uniplate::derive_unplateable!(Name);

impl Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Name::User(s) => write!(f, "{s}"),
            Name::Machine(i) => write!(f, "__{i}"),
            Name::Repr(fields) => {
                let (name, rule_string, suffix) = fields.as_ref();
                write!(f, "{name}#{rule_string}_{suffix}")
            }
        }
    }
}

impl From<&str> for Name {
    fn from(s: &str) -> Self {
        Name::User(Ustr::from(s))
    }
}

impl From<i32> for Name {
    fn from(i: i32) -> Self {
        Name::Machine(i)
    }
}
