[package]
name = "conjure-cp"
version = "0.1.0"
edition = "2024"

[dependencies]
conjure-cp-core = { version = "0.0.1", path = "../conjure-cp-core", default-features = false }
conjure-cp-essence-macros = { version = "0.1.0", path = "../conjure-cp-essence-macros" }
conjure-cp-essence-parser = { version = "0.1.0", path = "../conjure-cp-essence-parser", default-features = false }

[features]
default = ["sat-cadical", "z3"]
sat-cadical = ["conjure-cp-core/sat-cadical", "conjure-cp-essence-parser/sat-cadical"]
sat-batsat = ["conjure-cp-core/sat-batsat", "conjure-cp-essence-parser/sat-batsat"]
z3 = ["conjure-cp-core/z3"]
z3-bundled = [
    "conjure-cp-core/z3-bundled",
    "conjure-cp-essence-macros/z3-bundled",
    "conjure-cp-essence-parser/z3-bundled",
]
extra-rule-checks = ["conjure-cp-core/extra-rule-checks"]

[lints]
workspace = true

[dev-dependencies]
conjure-cp-rules = { path = '../conjure-cp-rules', default-features = false }

defile = { workspace = true }
itertools = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-haskell = { workspace = true }
uniplate = { workspace = true }
