[package]
name = "kissat_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kissat-rs = { git = "https://github.com/firefighterduck/kissat-rs", rev = "45cc75e369c8215c826647f100f4fd0eee3198e9", version = "0.1" }
kissat-sys = { git = "https://github.com/firefighterduck/kissat-rs", rev = "45cc75e369c8215c826647f100f4fd0eee3198e9", version = "0.1" }
