#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 55
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_suchthat = 1,
  anon_sym_find = 2,
  anon_sym_COLON = 3,
  anon_sym_COMMA = 4,
  anon_sym_int = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_DOT_DOT = 8,
  sym_identifier = 9,
  anon_sym_or = 10,
  anon_sym_and = 11,
  anon_sym_PLUS = 12,
  anon_sym_DASH = 13,
  anon_sym_STAR = 14,
  anon_sym_SLASH = 15,
  anon_sym_EQ = 16,
  anon_sym_BANG_EQ = 17,
  anon_sym_LT_EQ = 18,
  anon_sym_GT_EQ = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  sym_integer = 22,
  sym_program = 23,
  sym_find_statement = 24,
  sym_variable_list = 25,
  sym_constraint = 26,
  sym_domain = 27,
  sym_range = 28,
  sym_variable = 29,
  sym_expression = 30,
  sym_conjunction = 31,
  sym_comparison = 32,
  sym_addition = 33,
  sym_term = 34,
  sym_factor = 35,
  sym_comp_op = 36,
  sym_constant = 37,
  aux_sym_variable_list_repeat1 = 38,
  aux_sym_expression_repeat1 = 39,
  aux_sym_conjunction_repeat1 = 40,
  aux_sym_comparison_repeat1 = 41,
  aux_sym_addition_repeat1 = 42,
  aux_sym_term_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_suchthat] = "such that",
  [anon_sym_find] = "find",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_int] = "int",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DOT_DOT] = "..",
  [sym_identifier] = "identifier",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_integer] = "integer",
  [sym_program] = "program",
  [sym_find_statement] = "find_statement",
  [sym_variable_list] = "variable_list",
  [sym_constraint] = "constraint",
  [sym_domain] = "domain",
  [sym_range] = "range",
  [sym_variable] = "variable",
  [sym_expression] = "expression",
  [sym_conjunction] = "conjunction",
  [sym_comparison] = "comparison",
  [sym_addition] = "addition",
  [sym_term] = "term",
  [sym_factor] = "factor",
  [sym_comp_op] = "comp_op",
  [sym_constant] = "constant",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_conjunction_repeat1] = "conjunction_repeat1",
  [aux_sym_comparison_repeat1] = "comparison_repeat1",
  [aux_sym_addition_repeat1] = "addition_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_suchthat] = anon_sym_suchthat,
  [anon_sym_find] = anon_sym_find,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_integer] = sym_integer,
  [sym_program] = sym_program,
  [sym_find_statement] = sym_find_statement,
  [sym_variable_list] = sym_variable_list,
  [sym_constraint] = sym_constraint,
  [sym_domain] = sym_domain,
  [sym_range] = sym_range,
  [sym_variable] = sym_variable,
  [sym_expression] = sym_expression,
  [sym_conjunction] = sym_conjunction,
  [sym_comparison] = sym_comparison,
  [sym_addition] = sym_addition,
  [sym_term] = sym_term,
  [sym_factor] = sym_factor,
  [sym_comp_op] = sym_comp_op,
  [sym_constant] = sym_constant,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_conjunction_repeat1] = aux_sym_conjunction_repeat1,
  [aux_sym_comparison_repeat1] = aux_sym_comparison_repeat1,
  [aux_sym_addition_repeat1] = aux_sym_addition_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_suchthat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_find] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_find_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comparison_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_addition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 4,
        '(', 26,
        ')', 27,
        '*', 34,
        '+', 32,
        ',', 24,
        '-', 33,
        '.', 3,
        '/', 35,
        ':', 23,
        '<', 40,
        '=', 36,
        '>', 41,
        'a', 12,
        'f', 11,
        'i', 13,
        'o', 15,
        's', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(1);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(25);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_suchthat);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_find);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_suchthat] = ACTIONS(1),
    [anon_sym_find] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(44),
    [sym_find_statement] = STATE(46),
    [anon_sym_find] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(7), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(5), 14,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [21] = 4,
    STATE(4), 1,
      aux_sym_term_repeat1,
    ACTIONS(11), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(13), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(9), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [45] = 4,
    STATE(5), 1,
      aux_sym_term_repeat1,
    ACTIONS(11), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(17), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [69] = 4,
    STATE(5), 1,
      aux_sym_term_repeat1,
    ACTIONS(21), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(24), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(19), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [93] = 2,
    ACTIONS(28), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(26), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [112] = 2,
    ACTIONS(32), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(30), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [131] = 2,
    ACTIONS(36), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(34), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [150] = 2,
    ACTIONS(24), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(19), 12,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [169] = 4,
    STATE(12), 1,
      aux_sym_addition_repeat1,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(42), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(38), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [191] = 4,
    STATE(11), 1,
      aux_sym_addition_repeat1,
    ACTIONS(46), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [213] = 4,
    STATE(11), 1,
      aux_sym_addition_repeat1,
    ACTIONS(40), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(51), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [235] = 5,
    STATE(15), 1,
      aux_sym_comparison_repeat1,
    STATE(22), 1,
      sym_comp_op,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(57), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [258] = 11,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(10), 1,
      sym_term,
    STATE(13), 1,
      sym_addition,
    STATE(25), 1,
      sym_comparison,
    STATE(30), 1,
      sym_conjunction,
    STATE(43), 1,
      sym_constraint,
    STATE(45), 1,
      sym_expression,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [293] = 5,
    STATE(16), 1,
      aux_sym_comparison_repeat1,
    STATE(22), 1,
      sym_comp_op,
    ACTIONS(59), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(67), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [316] = 5,
    STATE(16), 1,
      aux_sym_comparison_repeat1,
    STATE(22), 1,
      sym_comp_op,
    ACTIONS(74), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(71), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [339] = 2,
    ACTIONS(49), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 10,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [356] = 10,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(10), 1,
      sym_term,
    STATE(13), 1,
      sym_addition,
    STATE(25), 1,
      sym_comparison,
    STATE(30), 1,
      sym_conjunction,
    STATE(49), 1,
      sym_expression,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [388] = 9,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(10), 1,
      sym_term,
    STATE(13), 1,
      sym_addition,
    STATE(25), 1,
      sym_comparison,
    STATE(35), 1,
      sym_conjunction,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [417] = 2,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(69), 8,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [432] = 8,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(10), 1,
      sym_term,
    STATE(13), 1,
      sym_addition,
    STATE(28), 1,
      sym_comparison,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [458] = 7,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(10), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [481] = 6,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [501] = 5,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      sym_identifier,
    ACTIONS(65), 1,
      sym_integer,
    STATE(9), 1,
      sym_factor,
    STATE(7), 2,
      sym_variable,
      sym_constant,
  [518] = 3,
    ACTIONS(81), 1,
      anon_sym_and,
    STATE(26), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
  [530] = 3,
    ACTIONS(81), 1,
      anon_sym_and,
    STATE(27), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
  [542] = 3,
    ACTIONS(87), 1,
      anon_sym_and,
    STATE(27), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
  [554] = 1,
    ACTIONS(85), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [561] = 3,
    ACTIONS(92), 1,
      anon_sym_or,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [572] = 3,
    ACTIONS(97), 1,
      anon_sym_or,
    STATE(31), 1,
      aux_sym_expression_repeat1,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [583] = 3,
    ACTIONS(97), 1,
      anon_sym_or,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
  [594] = 1,
    ACTIONS(101), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [600] = 3,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    STATE(37), 1,
      aux_sym_variable_list_repeat1,
  [610] = 3,
    ACTIONS(63), 1,
      sym_identifier,
    STATE(33), 1,
      sym_variable,
    STATE(42), 1,
      sym_variable_list,
  [620] = 1,
    ACTIONS(90), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_or,
  [626] = 3,
    ACTIONS(107), 1,
      anon_sym_COLON,
    ACTIONS(109), 1,
      anon_sym_COMMA,
    STATE(36), 1,
      aux_sym_variable_list_repeat1,
  [636] = 3,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    ACTIONS(112), 1,
      anon_sym_COLON,
    STATE(36), 1,
      aux_sym_variable_list_repeat1,
  [646] = 2,
    ACTIONS(114), 1,
      anon_sym_int,
    STATE(47), 1,
      sym_domain,
  [653] = 2,
    ACTIONS(116), 1,
      sym_integer,
    STATE(51), 1,
      sym_range,
  [660] = 2,
    ACTIONS(63), 1,
      sym_identifier,
    STATE(41), 1,
      sym_variable,
  [667] = 1,
    ACTIONS(107), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [672] = 1,
    ACTIONS(118), 1,
      anon_sym_COLON,
  [676] = 1,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
  [680] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [684] = 1,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
  [688] = 1,
    ACTIONS(126), 1,
      anon_sym_suchthat,
  [692] = 1,
    ACTIONS(128), 1,
      anon_sym_suchthat,
  [696] = 1,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
  [700] = 1,
    ACTIONS(132), 1,
      anon_sym_RPAREN,
  [704] = 1,
    ACTIONS(134), 1,
      anon_sym_DOT_DOT,
  [708] = 1,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
  [712] = 1,
    ACTIONS(138), 1,
      sym_integer,
  [716] = 1,
    ACTIONS(140), 1,
      anon_sym_suchthat,
  [720] = 1,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 45,
  [SMALL_STATE(5)] = 69,
  [SMALL_STATE(6)] = 93,
  [SMALL_STATE(7)] = 112,
  [SMALL_STATE(8)] = 131,
  [SMALL_STATE(9)] = 150,
  [SMALL_STATE(10)] = 169,
  [SMALL_STATE(11)] = 191,
  [SMALL_STATE(12)] = 213,
  [SMALL_STATE(13)] = 235,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 293,
  [SMALL_STATE(16)] = 316,
  [SMALL_STATE(17)] = 339,
  [SMALL_STATE(18)] = 356,
  [SMALL_STATE(19)] = 388,
  [SMALL_STATE(20)] = 417,
  [SMALL_STATE(21)] = 432,
  [SMALL_STATE(22)] = 458,
  [SMALL_STATE(23)] = 481,
  [SMALL_STATE(24)] = 501,
  [SMALL_STATE(25)] = 518,
  [SMALL_STATE(26)] = 530,
  [SMALL_STATE(27)] = 542,
  [SMALL_STATE(28)] = 554,
  [SMALL_STATE(29)] = 561,
  [SMALL_STATE(30)] = 572,
  [SMALL_STATE(31)] = 583,
  [SMALL_STATE(32)] = 594,
  [SMALL_STATE(33)] = 600,
  [SMALL_STATE(34)] = 610,
  [SMALL_STATE(35)] = 620,
  [SMALL_STATE(36)] = 626,
  [SMALL_STATE(37)] = 636,
  [SMALL_STATE(38)] = 646,
  [SMALL_STATE(39)] = 653,
  [SMALL_STATE(40)] = 660,
  [SMALL_STATE(41)] = 667,
  [SMALL_STATE(42)] = 672,
  [SMALL_STATE(43)] = 676,
  [SMALL_STATE(44)] = 680,
  [SMALL_STATE(45)] = 684,
  [SMALL_STATE(46)] = 688,
  [SMALL_STATE(47)] = 692,
  [SMALL_STATE(48)] = 696,
  [SMALL_STATE(49)] = 700,
  [SMALL_STATE(50)] = 704,
  [SMALL_STATE(51)] = 708,
  [SMALL_STATE(52)] = 712,
  [SMALL_STATE(53)] = 716,
  [SMALL_STATE(54)] = 720,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [24] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 3, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 3, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 4, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_essence(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
