#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_single_line_comment = 1,
  anon_sym_find = 2,
  anon_sym_COLON = 3,
  anon_sym_COMMA = 4,
  anon_sym_suchthat = 5,
  anon_sym_int = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  sym_bool_domain = 9,
  anon_sym_DOT_DOT = 10,
  sym_identifier = 11,
  anon_sym_or = 12,
  anon_sym_and = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_min_LPAREN_LBRACK = 18,
  anon_sym_RBRACK_RPAREN = 19,
  anon_sym_max_LPAREN_LBRACK = 20,
  sym_TRUE = 21,
  sym_FALSE = 22,
  anon_sym_EQ = 23,
  anon_sym_BANG_EQ = 24,
  anon_sym_LT_EQ = 25,
  anon_sym_GT_EQ = 26,
  anon_sym_LT = 27,
  anon_sym_GT = 28,
  sym_integer = 29,
  sym_program = 30,
  sym_find_statement_list = 31,
  sym_find_statement = 32,
  sym_variable_list = 33,
  sym_constraint_list = 34,
  sym_constraint = 35,
  sym_domain = 36,
  sym_int_domain = 37,
  sym_range_list = 38,
  sym_lower_bound_range = 39,
  sym_upper_bound_range = 40,
  sym_closed_range = 41,
  sym_variable = 42,
  sym_expression = 43,
  sym_conjunction = 44,
  sym_comparison = 45,
  sym_addition = 46,
  sym_term = 47,
  sym_factor = 48,
  sym_min = 49,
  sym_max = 50,
  sym_comp_op = 51,
  sym_constant = 52,
  aux_sym_program_repeat1 = 53,
  aux_sym_find_statement_list_repeat1 = 54,
  aux_sym_variable_list_repeat1 = 55,
  aux_sym_constraint_list_repeat1 = 56,
  aux_sym_range_list_repeat1 = 57,
  aux_sym_expression_repeat1 = 58,
  aux_sym_conjunction_repeat1 = 59,
  aux_sym_comparison_repeat1 = 60,
  aux_sym_addition_repeat1 = 61,
  aux_sym_term_repeat1 = 62,
  aux_sym_min_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_single_line_comment] = "single_line_comment",
  [anon_sym_find] = "find",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_suchthat] = "such that",
  [anon_sym_int] = "int",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_bool_domain] = "bool_domain",
  [anon_sym_DOT_DOT] = "..",
  [sym_identifier] = "identifier",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_min_LPAREN_LBRACK] = "min([",
  [anon_sym_RBRACK_RPAREN] = "])",
  [anon_sym_max_LPAREN_LBRACK] = "max([",
  [sym_TRUE] = "TRUE",
  [sym_FALSE] = "FALSE",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_integer] = "integer",
  [sym_program] = "program",
  [sym_find_statement_list] = "find_statement_list",
  [sym_find_statement] = "find_statement",
  [sym_variable_list] = "variable_list",
  [sym_constraint_list] = "constraint_list",
  [sym_constraint] = "constraint",
  [sym_domain] = "domain",
  [sym_int_domain] = "int_domain",
  [sym_range_list] = "range_list",
  [sym_lower_bound_range] = "lower_bound_range",
  [sym_upper_bound_range] = "upper_bound_range",
  [sym_closed_range] = "closed_range",
  [sym_variable] = "variable",
  [sym_expression] = "expression",
  [sym_conjunction] = "conjunction",
  [sym_comparison] = "comparison",
  [sym_addition] = "addition",
  [sym_term] = "term",
  [sym_factor] = "factor",
  [sym_min] = "min",
  [sym_max] = "max",
  [sym_comp_op] = "comp_op",
  [sym_constant] = "constant",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_find_statement_list_repeat1] = "find_statement_list_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_constraint_list_repeat1] = "constraint_list_repeat1",
  [aux_sym_range_list_repeat1] = "range_list_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_conjunction_repeat1] = "conjunction_repeat1",
  [aux_sym_comparison_repeat1] = "comparison_repeat1",
  [aux_sym_addition_repeat1] = "addition_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_min_repeat1] = "min_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_single_line_comment] = sym_single_line_comment,
  [anon_sym_find] = anon_sym_find,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_suchthat] = anon_sym_suchthat,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_bool_domain] = sym_bool_domain,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_min_LPAREN_LBRACK] = anon_sym_min_LPAREN_LBRACK,
  [anon_sym_RBRACK_RPAREN] = anon_sym_RBRACK_RPAREN,
  [anon_sym_max_LPAREN_LBRACK] = anon_sym_max_LPAREN_LBRACK,
  [sym_TRUE] = sym_TRUE,
  [sym_FALSE] = sym_FALSE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_integer] = sym_integer,
  [sym_program] = sym_program,
  [sym_find_statement_list] = sym_find_statement_list,
  [sym_find_statement] = sym_find_statement,
  [sym_variable_list] = sym_variable_list,
  [sym_constraint_list] = sym_constraint_list,
  [sym_constraint] = sym_constraint,
  [sym_domain] = sym_domain,
  [sym_int_domain] = sym_int_domain,
  [sym_range_list] = sym_range_list,
  [sym_lower_bound_range] = sym_lower_bound_range,
  [sym_upper_bound_range] = sym_upper_bound_range,
  [sym_closed_range] = sym_closed_range,
  [sym_variable] = sym_variable,
  [sym_expression] = sym_expression,
  [sym_conjunction] = sym_conjunction,
  [sym_comparison] = sym_comparison,
  [sym_addition] = sym_addition,
  [sym_term] = sym_term,
  [sym_factor] = sym_factor,
  [sym_min] = sym_min,
  [sym_max] = sym_max,
  [sym_comp_op] = sym_comp_op,
  [sym_constant] = sym_constant,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_find_statement_list_repeat1] = aux_sym_find_statement_list_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_constraint_list_repeat1] = aux_sym_constraint_list_repeat1,
  [aux_sym_range_list_repeat1] = aux_sym_range_list_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_conjunction_repeat1] = aux_sym_conjunction_repeat1,
  [aux_sym_comparison_repeat1] = aux_sym_comparison_repeat1,
  [aux_sym_addition_repeat1] = aux_sym_addition_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_min_repeat1] = aux_sym_min_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_find] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_suchthat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_bool_domain] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_LPAREN_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_LPAREN_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_TRUE] = {
    .visible = true,
    .named = true,
  },
  [sym_FALSE] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_find_statement_list] = {
    .visible = true,
    .named = true,
  },
  [sym_find_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint_list] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_int_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_range_list] = {
    .visible = true,
    .named = true,
  },
  [sym_lower_bound_range] = {
    .visible = true,
    .named = true,
  },
  [sym_upper_bound_range] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_range] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_min] = {
    .visible = true,
    .named = true,
  },
  [sym_max] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_find_statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraint_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_range_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comparison_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_addition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_min_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 29,
  [31] = 31,
  [32] = 3,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 2,
  [37] = 35,
  [38] = 5,
  [39] = 39,
  [40] = 40,
  [41] = 4,
  [42] = 7,
  [43] = 9,
  [44] = 44,
  [45] = 6,
  [46] = 13,
  [47] = 47,
  [48] = 8,
  [49] = 12,
  [50] = 10,
  [51] = 51,
  [52] = 11,
  [53] = 47,
  [54] = 16,
  [55] = 17,
  [56] = 19,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 23,
  [61] = 21,
  [62] = 20,
  [63] = 22,
  [64] = 64,
  [65] = 65,
  [66] = 24,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 31,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 33,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 34,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 86,
  [92] = 85,
  [93] = 88,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 44,
  [98] = 51,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 39,
  [103] = 103,
  [104] = 40,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 58,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 116,
  [118] = 118,
  [119] = 119,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 8,
        '$', 43,
        '(', 50,
        ')', 51,
        '*', 84,
        '+', 82,
        ',', 47,
        '-', 83,
        '.', 7,
        '/', 85,
        ':', 46,
        '<', 97,
        '=', 93,
        '>', 98,
        ']', 6,
        'a', 23,
        'b', 27,
        'f', 11,
        'i', 24,
        'm', 12,
        'o', 29,
        's', 35,
        't', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(58);
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == 't') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(43);
      if (lookahead == ']') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == ')') ADVANCE(87);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(94);
      END_STATE();
    case 9:
      if (lookahead == '[') ADVANCE(88);
      END_STATE();
    case 10:
      if (lookahead == '[') ADVANCE(86);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(80);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(44);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 19:
      if (lookahead == 'h') ADVANCE(1);
      END_STATE();
    case 20:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 36:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 37:
      if (lookahead == 'x') ADVANCE(4);
      END_STATE();
    case 38:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '!', 8,
        '$', 43,
        '(', 50,
        '*', 84,
        '+', 82,
        ',', 47,
        '-', 83,
        '/', 85,
        ':', 46,
        '<', 97,
        '=', 93,
        '>', 98,
        'a', 68,
        'f', 57,
        'm', 59,
        'o', 71,
        's', 74,
        't', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 39:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        '$', 43,
        '(', 50,
        ',', 47,
        'f', 57,
        'm', 59,
        'o', 71,
        's', 74,
        't', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 40:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(57);
      if (lookahead == 'm') ADVANCE(59);
      if (lookahead == 's') ADVANCE(74);
      if (lookahead == 't') ADVANCE(72);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 41:
      if (eof) ADVANCE(42);
      if (lookahead == '$') ADVANCE(43);
      if (lookahead == '(') ADVANCE(50);
      if (lookahead == ',') ADVANCE(47);
      if (lookahead == 'f') ADVANCE(66);
      if (lookahead == 's') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(41);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_single_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_find);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_find);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_suchthat);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_bool_domain);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(67);
      if (lookahead == 'i') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(76);
      if (lookahead == 'i') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_min_LPAREN_LBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_RBRACK_RPAREN);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_max_LPAREN_LBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_TRUE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_TRUE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_FALSE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_FALSE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(96);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 38},
  [3] = {.lex_state = 38},
  [4] = {.lex_state = 38},
  [5] = {.lex_state = 38},
  [6] = {.lex_state = 38},
  [7] = {.lex_state = 38},
  [8] = {.lex_state = 38},
  [9] = {.lex_state = 38},
  [10] = {.lex_state = 38},
  [11] = {.lex_state = 38},
  [12] = {.lex_state = 38},
  [13] = {.lex_state = 38},
  [14] = {.lex_state = 40},
  [15] = {.lex_state = 40},
  [16] = {.lex_state = 38},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 40},
  [19] = {.lex_state = 38},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 38},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 38},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 38},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 38},
  [34] = {.lex_state = 38},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 39},
  [40] = {.lex_state = 38},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 39},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 39},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 39},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 40},
  [65] = {.lex_state = 40},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 41},
  [68] = {.lex_state = 41},
  [69] = {.lex_state = 41},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 41},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 41},
  [76] = {.lex_state = 41},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 41},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 41},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_single_line_comment] = ACTIONS(3),
    [anon_sym_find] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_suchthat] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_bool_domain] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_min_LPAREN_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RPAREN] = ACTIONS(1),
    [anon_sym_max_LPAREN_LBRACK] = ACTIONS(1),
    [sym_TRUE] = ACTIONS(1),
    [sym_FALSE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(118),
    [sym_find_statement_list] = STATE(72),
    [sym_constraint_list] = STATE(72),
    [aux_sym_program_repeat1] = STATE(72),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_single_line_comment] = ACTIONS(3),
    [anon_sym_find] = ACTIONS(7),
    [anon_sym_suchthat] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(5), 1,
      aux_sym_term_repeat1,
    ACTIONS(15), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(13), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [36] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(2), 1,
      aux_sym_term_repeat1,
    ACTIONS(15), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(19), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(17), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [72] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(23), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 16,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [104] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(5), 1,
      aux_sym_term_repeat1,
    ACTIONS(29), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(27), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [140] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(34), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(32), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [171] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(38), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(36), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [202] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(42), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(40), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [233] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(46), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [264] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(50), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [295] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(27), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [326] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(54), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(52), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [357] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(58), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(56), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [388] = 17,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(62), 1,
      anon_sym_find,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(33), 1,
      sym_comparison,
    STATE(44), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(18), 2,
      sym_constraint,
      aux_sym_constraint_list_repeat1,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [446] = 17,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(78), 1,
      anon_sym_find,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(86), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(89), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(95), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(33), 1,
      sym_comparison,
    STATE(44), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(92), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(15), 2,
      sym_constraint,
      aux_sym_constraint_list_repeat1,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [504] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(19), 1,
      aux_sym_addition_repeat1,
    ACTIONS(102), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(100), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(98), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [538] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(16), 1,
      aux_sym_addition_repeat1,
    ACTIONS(102), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(106), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [572] = 17,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    ACTIONS(110), 1,
      anon_sym_find,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(33), 1,
      sym_comparison,
    STATE(44), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(15), 2,
      sym_constraint,
      aux_sym_constraint_list_repeat1,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [630] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(19), 1,
      aux_sym_addition_repeat1,
    ACTIONS(116), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(114), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(112), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [664] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(22), 1,
      aux_sym_comparison_repeat1,
    STATE(37), 1,
      sym_comp_op,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(121), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(119), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [701] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(114), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(112), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [730] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(23), 1,
      aux_sym_comparison_repeat1,
    STATE(37), 1,
      sym_comp_op,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(123), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(129), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [767] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(23), 1,
      aux_sym_comparison_repeat1,
    STATE(37), 1,
      sym_comp_op,
    ACTIONS(138), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(135), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(133), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(131), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [804] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(133), 8,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [831] = 14,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(55), 1,
      sym_term,
    STATE(62), 1,
      sym_addition,
    STATE(83), 1,
      sym_comparison,
    STATE(97), 1,
      sym_conjunction,
    STATE(117), 1,
      sym_expression,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [878] = 14,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(55), 1,
      sym_term,
    STATE(62), 1,
      sym_addition,
    STATE(83), 1,
      sym_comparison,
    STATE(97), 1,
      sym_conjunction,
    STATE(116), 1,
      sym_expression,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [925] = 13,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(55), 1,
      sym_term,
    STATE(62), 1,
      sym_addition,
    STATE(83), 1,
      sym_comparison,
    STATE(111), 1,
      sym_conjunction,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [969] = 13,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(33), 1,
      sym_comparison,
    STATE(58), 1,
      sym_conjunction,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1013] = 12,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(20), 1,
      sym_addition,
    STATE(40), 1,
      sym_comparison,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1054] = 12,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(55), 1,
      sym_term,
    STATE(62), 1,
      sym_addition,
    STATE(104), 1,
      sym_comparison,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1095] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(157), 1,
      anon_sym_and,
    STATE(34), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(155), 5,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1121] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(36), 1,
      aux_sym_term_repeat1,
    ACTIONS(19), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(159), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(17), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1147] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(157), 1,
      anon_sym_and,
    STATE(31), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(163), 5,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(161), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1173] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(169), 1,
      anon_sym_and,
    STATE(34), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(167), 5,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(165), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1199] = 11,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(55), 1,
      sym_term,
    STATE(66), 1,
      sym_addition,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1237] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(38), 1,
      aux_sym_term_repeat1,
    ACTIONS(13), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(159), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(11), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1263] = 11,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(17), 1,
      sym_term,
    STATE(24), 1,
      sym_addition,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1301] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(38), 1,
      aux_sym_term_repeat1,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(172), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(25), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1327] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(179), 1,
      anon_sym_or,
    STATE(39), 1,
      aux_sym_expression_repeat1,
    ACTIONS(177), 4,
      anon_sym_find,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1352] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(167), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(165), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1373] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1394] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(38), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(36), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1415] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(46), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1436] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(186), 1,
      anon_sym_or,
    STATE(51), 1,
      aux_sym_expression_repeat1,
    ACTIONS(184), 4,
      anon_sym_find,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(182), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1461] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(34), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(32), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1482] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(58), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(56), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1503] = 10,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(32), 1,
      sym_factor,
    STATE(61), 1,
      sym_term,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1538] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(42), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(40), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1559] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(54), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(52), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1580] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(50), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1601] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(186), 1,
      anon_sym_or,
    STATE(39), 1,
      aux_sym_expression_repeat1,
    ACTIONS(190), 4,
      anon_sym_find,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(188), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1626] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(27), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(25), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1647] = 10,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(21), 1,
      sym_term,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1682] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(56), 1,
      aux_sym_addition_repeat1,
    ACTIONS(100), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(192), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(98), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1706] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(54), 1,
      aux_sym_addition_repeat1,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(192), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(104), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1730] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(56), 1,
      aux_sym_addition_repeat1,
    ACTIONS(114), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(194), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(112), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1754] = 9,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(64), 1,
      anon_sym_LPAREN,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(70), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(74), 1,
      sym_integer,
    STATE(11), 1,
      sym_factor,
    ACTIONS(72), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(9), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1786] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(177), 5,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1806] = 9,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(141), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      sym_identifier,
    ACTIONS(145), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(147), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(151), 1,
      sym_integer,
    STATE(52), 1,
      sym_factor,
    ACTIONS(149), 2,
      sym_TRUE,
      sym_FALSE,
    STATE(43), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1838] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(35), 1,
      sym_comp_op,
    STATE(60), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(138), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(135), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1863] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(114), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(112), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1882] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(35), 1,
      sym_comp_op,
    STATE(63), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(123), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1907] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(35), 1,
      sym_comp_op,
    STATE(60), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(125), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(127), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(123), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1932] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    ACTIONS(199), 4,
      anon_sym_find,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(197), 6,
      ts_builtin_sym_end,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1953] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(205), 4,
      anon_sym_find,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(203), 6,
      ts_builtin_sym_end,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1971] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(131), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1988] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(209), 1,
      anon_sym_find,
    ACTIONS(211), 1,
      sym_identifier,
    STATE(95), 1,
      sym_variable,
    STATE(114), 1,
      sym_variable_list,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(67), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [2012] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(216), 1,
      anon_sym_find,
    STATE(95), 1,
      sym_variable,
    STATE(114), 1,
      sym_variable_list,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(67), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [2036] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(66), 1,
      sym_identifier,
    ACTIONS(220), 1,
      anon_sym_find,
    STATE(95), 1,
      sym_variable,
    STATE(114), 1,
      sym_variable_list,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(68), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [2060] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(224), 3,
      sym_identifier,
      sym_TRUE,
      sym_FALSE,
    ACTIONS(222), 4,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [2075] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(230), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(226), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [2091] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(7), 1,
      anon_sym_find,
    ACTIONS(9), 1,
      anon_sym_suchthat,
    ACTIONS(232), 1,
      ts_builtin_sym_end,
    STATE(73), 3,
      sym_find_statement_list,
      sym_constraint_list,
      aux_sym_program_repeat1,
  [2109] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(234), 1,
      ts_builtin_sym_end,
    ACTIONS(236), 1,
      anon_sym_find,
    ACTIONS(239), 1,
      anon_sym_suchthat,
    STATE(73), 3,
      sym_find_statement_list,
      sym_constraint_list,
      aux_sym_program_repeat1,
  [2127] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(242), 1,
      anon_sym_DOT_DOT,
    ACTIONS(244), 1,
      sym_integer,
    STATE(119), 1,
      sym_range_list,
    STATE(96), 3,
      sym_lower_bound_range,
      sym_upper_bound_range,
      sym_closed_range,
  [2145] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(248), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(246), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [2158] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(250), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(252), 2,
      anon_sym_find,
      sym_identifier,
  [2173] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(242), 1,
      anon_sym_DOT_DOT,
    ACTIONS(256), 1,
      sym_integer,
    STATE(107), 3,
      sym_lower_bound_range,
      sym_upper_bound_range,
      sym_closed_range,
  [2188] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(260), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(258), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [2201] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(262), 1,
      anon_sym_and,
    STATE(87), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(153), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2215] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(264), 1,
      anon_sym_int,
    ACTIONS(266), 1,
      sym_bool_domain,
    STATE(75), 1,
      sym_int_domain,
    STATE(76), 1,
      sym_domain,
  [2231] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      anon_sym_DOT_DOT,
    STATE(101), 1,
      aux_sym_range_list_repeat1,
  [2247] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(274), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(276), 2,
      anon_sym_find,
      sym_identifier,
  [2259] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(262), 1,
      anon_sym_and,
    STATE(79), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2273] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(278), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(84), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2289] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(285), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(84), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2305] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(84), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2321] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(289), 1,
      anon_sym_and,
    STATE(87), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(165), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2335] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(292), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(92), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2351] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(294), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(86), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2367] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(296), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(91), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2383] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(298), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(84), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2399] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(300), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(84), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2415] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(302), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(113), 1,
      sym_variable,
  [2431] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(304), 1,
      anon_sym_COLON,
    ACTIONS(306), 1,
      anon_sym_COMMA,
    STATE(100), 1,
      aux_sym_variable_list_repeat1,
  [2444] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(306), 1,
      anon_sym_COMMA,
    ACTIONS(308), 1,
      anon_sym_COLON,
    STATE(94), 1,
      aux_sym_variable_list_repeat1,
  [2457] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      aux_sym_range_list_repeat1,
  [2470] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      anon_sym_or,
    STATE(98), 1,
      aux_sym_expression_repeat1,
  [2483] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(188), 1,
      anon_sym_RPAREN,
    ACTIONS(310), 1,
      anon_sym_or,
    STATE(102), 1,
      aux_sym_expression_repeat1,
  [2496] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(314), 1,
      sym_integer,
    ACTIONS(312), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2507] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(316), 1,
      anon_sym_COLON,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    STATE(100), 1,
      aux_sym_variable_list_repeat1,
  [2520] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(321), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_range_list_repeat1,
  [2533] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(323), 1,
      anon_sym_or,
    STATE(102), 1,
      aux_sym_expression_repeat1,
  [2546] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(326), 1,
      anon_sym_COMMA,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_range_list_repeat1,
  [2559] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(165), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [2568] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(272), 1,
      anon_sym_DOT_DOT,
    ACTIONS(329), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2579] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(283), 1,
      sym_identifier,
    STATE(108), 1,
      sym_variable,
  [2589] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(329), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2597] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(316), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2605] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(331), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2613] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(333), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2621] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(175), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2629] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(281), 2,
      sym_identifier,
      anon_sym_RBRACK_RPAREN,
  [2637] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(335), 1,
      anon_sym_COMMA,
  [2644] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(337), 1,
      anon_sym_COLON,
  [2651] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(339), 1,
      sym_integer,
  [2658] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
  [2665] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(343), 1,
      anon_sym_RPAREN,
  [2672] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(345), 1,
      ts_builtin_sym_end,
  [2679] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 36,
  [SMALL_STATE(4)] = 72,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 171,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 233,
  [SMALL_STATE(10)] = 264,
  [SMALL_STATE(11)] = 295,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 357,
  [SMALL_STATE(14)] = 388,
  [SMALL_STATE(15)] = 446,
  [SMALL_STATE(16)] = 504,
  [SMALL_STATE(17)] = 538,
  [SMALL_STATE(18)] = 572,
  [SMALL_STATE(19)] = 630,
  [SMALL_STATE(20)] = 664,
  [SMALL_STATE(21)] = 701,
  [SMALL_STATE(22)] = 730,
  [SMALL_STATE(23)] = 767,
  [SMALL_STATE(24)] = 804,
  [SMALL_STATE(25)] = 831,
  [SMALL_STATE(26)] = 878,
  [SMALL_STATE(27)] = 925,
  [SMALL_STATE(28)] = 969,
  [SMALL_STATE(29)] = 1013,
  [SMALL_STATE(30)] = 1054,
  [SMALL_STATE(31)] = 1095,
  [SMALL_STATE(32)] = 1121,
  [SMALL_STATE(33)] = 1147,
  [SMALL_STATE(34)] = 1173,
  [SMALL_STATE(35)] = 1199,
  [SMALL_STATE(36)] = 1237,
  [SMALL_STATE(37)] = 1263,
  [SMALL_STATE(38)] = 1301,
  [SMALL_STATE(39)] = 1327,
  [SMALL_STATE(40)] = 1352,
  [SMALL_STATE(41)] = 1373,
  [SMALL_STATE(42)] = 1394,
  [SMALL_STATE(43)] = 1415,
  [SMALL_STATE(44)] = 1436,
  [SMALL_STATE(45)] = 1461,
  [SMALL_STATE(46)] = 1482,
  [SMALL_STATE(47)] = 1503,
  [SMALL_STATE(48)] = 1538,
  [SMALL_STATE(49)] = 1559,
  [SMALL_STATE(50)] = 1580,
  [SMALL_STATE(51)] = 1601,
  [SMALL_STATE(52)] = 1626,
  [SMALL_STATE(53)] = 1647,
  [SMALL_STATE(54)] = 1682,
  [SMALL_STATE(55)] = 1706,
  [SMALL_STATE(56)] = 1730,
  [SMALL_STATE(57)] = 1754,
  [SMALL_STATE(58)] = 1786,
  [SMALL_STATE(59)] = 1806,
  [SMALL_STATE(60)] = 1838,
  [SMALL_STATE(61)] = 1863,
  [SMALL_STATE(62)] = 1882,
  [SMALL_STATE(63)] = 1907,
  [SMALL_STATE(64)] = 1932,
  [SMALL_STATE(65)] = 1953,
  [SMALL_STATE(66)] = 1971,
  [SMALL_STATE(67)] = 1988,
  [SMALL_STATE(68)] = 2012,
  [SMALL_STATE(69)] = 2036,
  [SMALL_STATE(70)] = 2060,
  [SMALL_STATE(71)] = 2075,
  [SMALL_STATE(72)] = 2091,
  [SMALL_STATE(73)] = 2109,
  [SMALL_STATE(74)] = 2127,
  [SMALL_STATE(75)] = 2145,
  [SMALL_STATE(76)] = 2158,
  [SMALL_STATE(77)] = 2173,
  [SMALL_STATE(78)] = 2188,
  [SMALL_STATE(79)] = 2201,
  [SMALL_STATE(80)] = 2215,
  [SMALL_STATE(81)] = 2231,
  [SMALL_STATE(82)] = 2247,
  [SMALL_STATE(83)] = 2259,
  [SMALL_STATE(84)] = 2273,
  [SMALL_STATE(85)] = 2289,
  [SMALL_STATE(86)] = 2305,
  [SMALL_STATE(87)] = 2321,
  [SMALL_STATE(88)] = 2335,
  [SMALL_STATE(89)] = 2351,
  [SMALL_STATE(90)] = 2367,
  [SMALL_STATE(91)] = 2383,
  [SMALL_STATE(92)] = 2399,
  [SMALL_STATE(93)] = 2415,
  [SMALL_STATE(94)] = 2431,
  [SMALL_STATE(95)] = 2444,
  [SMALL_STATE(96)] = 2457,
  [SMALL_STATE(97)] = 2470,
  [SMALL_STATE(98)] = 2483,
  [SMALL_STATE(99)] = 2496,
  [SMALL_STATE(100)] = 2507,
  [SMALL_STATE(101)] = 2520,
  [SMALL_STATE(102)] = 2533,
  [SMALL_STATE(103)] = 2546,
  [SMALL_STATE(104)] = 2559,
  [SMALL_STATE(105)] = 2568,
  [SMALL_STATE(106)] = 2579,
  [SMALL_STATE(107)] = 2589,
  [SMALL_STATE(108)] = 2597,
  [SMALL_STATE(109)] = 2605,
  [SMALL_STATE(110)] = 2613,
  [SMALL_STATE(111)] = 2621,
  [SMALL_STATE(112)] = 2629,
  [SMALL_STATE(113)] = 2637,
  [SMALL_STATE(114)] = 2644,
  [SMALL_STATE(115)] = 2651,
  [SMALL_STATE(116)] = 2658,
  [SMALL_STATE(117)] = 2665,
  [SMALL_STATE(118)] = 2672,
  [SMALL_STATE(119)] = 2679,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_min, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 3, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_max, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_min, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_max, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_list, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_list, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_list_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint_list, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint_list, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 1, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 2, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement_list, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement_list, 2, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement_list, 1, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement_list, 1, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comp_op, 1, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_domain, 1, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_domain, 1, 0, 0),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_domain, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement, 3, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_domain, 4, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_domain, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_list, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement, 4, 0, 0),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_min_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_min_repeat1, 2, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lower_bound_range, 2, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [318] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_list, 2, 0, 0),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [326] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_range_list_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_range_list_repeat1, 2, 0, 0),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closed_range, 3, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_upper_bound_range, 2, 0, 0),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [345] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_essence(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
