#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 120
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_single_line_comment = 1,
  anon_sym_find = 2,
  anon_sym_COLON = 3,
  anon_sym_COMMA = 4,
  anon_sym_suchthat = 5,
  anon_sym_int = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  sym_bool_domain = 9,
  anon_sym_DOT_DOT = 10,
  sym_identifier = 11,
  anon_sym_or = 12,
  anon_sym_and = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_min_LPAREN_LBRACK = 18,
  anon_sym_RBRACK_RPAREN = 19,
  anon_sym_max_LPAREN_LBRACK = 20,
  anon_sym_EQ = 21,
  anon_sym_BANG_EQ = 22,
  anon_sym_LT_EQ = 23,
  anon_sym_GT_EQ = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  sym_integer = 27,
  sym_program = 28,
  sym_find_statement_list = 29,
  sym_find_statement = 30,
  sym_variable_list = 31,
  sym_constraint = 32,
  sym_domain = 33,
  sym_int_domain = 34,
  sym_range_list = 35,
  sym_lower_bound_range = 36,
  sym_upper_bound_range = 37,
  sym_closed_range = 38,
  sym_variable = 39,
  sym_expression = 40,
  sym_conjunction = 41,
  sym_comparison = 42,
  sym_addition = 43,
  sym_term = 44,
  sym_factor = 45,
  sym_min = 46,
  sym_max = 47,
  sym_comp_op = 48,
  sym_constant = 49,
  aux_sym_program_repeat1 = 50,
  aux_sym_find_statement_list_repeat1 = 51,
  aux_sym_variable_list_repeat1 = 52,
  aux_sym_constraint_repeat1 = 53,
  aux_sym_range_list_repeat1 = 54,
  aux_sym_expression_repeat1 = 55,
  aux_sym_conjunction_repeat1 = 56,
  aux_sym_comparison_repeat1 = 57,
  aux_sym_addition_repeat1 = 58,
  aux_sym_term_repeat1 = 59,
  aux_sym_min_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_single_line_comment] = "single_line_comment",
  [anon_sym_find] = "find",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_suchthat] = "such that",
  [anon_sym_int] = "int",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_bool_domain] = "bool_domain",
  [anon_sym_DOT_DOT] = "..",
  [sym_identifier] = "identifier",
  [anon_sym_or] = "or",
  [anon_sym_and] = "and",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_min_LPAREN_LBRACK] = "min([",
  [anon_sym_RBRACK_RPAREN] = "])",
  [anon_sym_max_LPAREN_LBRACK] = "max([",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_integer] = "integer",
  [sym_program] = "program",
  [sym_find_statement_list] = "find_statement_list",
  [sym_find_statement] = "find_statement",
  [sym_variable_list] = "variable_list",
  [sym_constraint] = "constraint",
  [sym_domain] = "domain",
  [sym_int_domain] = "int_domain",
  [sym_range_list] = "range_list",
  [sym_lower_bound_range] = "lower_bound_range",
  [sym_upper_bound_range] = "upper_bound_range",
  [sym_closed_range] = "closed_range",
  [sym_variable] = "variable",
  [sym_expression] = "expression",
  [sym_conjunction] = "conjunction",
  [sym_comparison] = "comparison",
  [sym_addition] = "addition",
  [sym_term] = "term",
  [sym_factor] = "factor",
  [sym_min] = "min",
  [sym_max] = "max",
  [sym_comp_op] = "comp_op",
  [sym_constant] = "constant",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_find_statement_list_repeat1] = "find_statement_list_repeat1",
  [aux_sym_variable_list_repeat1] = "variable_list_repeat1",
  [aux_sym_constraint_repeat1] = "constraint_repeat1",
  [aux_sym_range_list_repeat1] = "range_list_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_conjunction_repeat1] = "conjunction_repeat1",
  [aux_sym_comparison_repeat1] = "comparison_repeat1",
  [aux_sym_addition_repeat1] = "addition_repeat1",
  [aux_sym_term_repeat1] = "term_repeat1",
  [aux_sym_min_repeat1] = "min_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_single_line_comment] = sym_single_line_comment,
  [anon_sym_find] = anon_sym_find,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_suchthat] = anon_sym_suchthat,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_bool_domain] = sym_bool_domain,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_identifier] = sym_identifier,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_min_LPAREN_LBRACK] = anon_sym_min_LPAREN_LBRACK,
  [anon_sym_RBRACK_RPAREN] = anon_sym_RBRACK_RPAREN,
  [anon_sym_max_LPAREN_LBRACK] = anon_sym_max_LPAREN_LBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_integer] = sym_integer,
  [sym_program] = sym_program,
  [sym_find_statement_list] = sym_find_statement_list,
  [sym_find_statement] = sym_find_statement,
  [sym_variable_list] = sym_variable_list,
  [sym_constraint] = sym_constraint,
  [sym_domain] = sym_domain,
  [sym_int_domain] = sym_int_domain,
  [sym_range_list] = sym_range_list,
  [sym_lower_bound_range] = sym_lower_bound_range,
  [sym_upper_bound_range] = sym_upper_bound_range,
  [sym_closed_range] = sym_closed_range,
  [sym_variable] = sym_variable,
  [sym_expression] = sym_expression,
  [sym_conjunction] = sym_conjunction,
  [sym_comparison] = sym_comparison,
  [sym_addition] = sym_addition,
  [sym_term] = sym_term,
  [sym_factor] = sym_factor,
  [sym_min] = sym_min,
  [sym_max] = sym_max,
  [sym_comp_op] = sym_comp_op,
  [sym_constant] = sym_constant,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_find_statement_list_repeat1] = aux_sym_find_statement_list_repeat1,
  [aux_sym_variable_list_repeat1] = aux_sym_variable_list_repeat1,
  [aux_sym_constraint_repeat1] = aux_sym_constraint_repeat1,
  [aux_sym_range_list_repeat1] = aux_sym_range_list_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_conjunction_repeat1] = aux_sym_conjunction_repeat1,
  [aux_sym_comparison_repeat1] = aux_sym_comparison_repeat1,
  [aux_sym_addition_repeat1] = aux_sym_addition_repeat1,
  [aux_sym_term_repeat1] = aux_sym_term_repeat1,
  [aux_sym_min_repeat1] = aux_sym_min_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_single_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_find] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_suchthat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_bool_domain] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_LPAREN_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_max_LPAREN_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_find_statement_list] = {
    .visible = true,
    .named = true,
  },
  [sym_find_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_list] = {
    .visible = true,
    .named = true,
  },
  [sym_constraint] = {
    .visible = true,
    .named = true,
  },
  [sym_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_int_domain] = {
    .visible = true,
    .named = true,
  },
  [sym_range_list] = {
    .visible = true,
    .named = true,
  },
  [sym_lower_bound_range] = {
    .visible = true,
    .named = true,
  },
  [sym_upper_bound_range] = {
    .visible = true,
    .named = true,
  },
  [sym_closed_range] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conjunction] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison] = {
    .visible = true,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_min] = {
    .visible = true,
    .named = true,
  },
  [sym_max] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_constant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_find_statement_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constraint_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_range_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_conjunction_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comparison_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_addition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_min_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 5,
  [28] = 3,
  [29] = 29,
  [30] = 29,
  [31] = 4,
  [32] = 6,
  [33] = 7,
  [34] = 8,
  [35] = 2,
  [36] = 9,
  [37] = 37,
  [38] = 37,
  [39] = 12,
  [40] = 10,
  [41] = 11,
  [42] = 13,
  [43] = 15,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 14,
  [48] = 48,
  [49] = 16,
  [50] = 46,
  [51] = 23,
  [52] = 21,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 17,
  [57] = 57,
  [58] = 58,
  [59] = 20,
  [60] = 53,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 24,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 48,
  [84] = 45,
  [85] = 85,
  [86] = 86,
  [87] = 44,
  [88] = 88,
  [89] = 89,
  [90] = 89,
  [91] = 79,
  [92] = 81,
  [93] = 80,
  [94] = 58,
  [95] = 95,
  [96] = 96,
  [97] = 54,
  [98] = 55,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 57,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 61,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 116,
  [119] = 119,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 8,
        '$', 37,
        '(', 44,
        ')', 45,
        '*', 70,
        '+', 68,
        ',', 41,
        '-', 69,
        '.', 7,
        '/', 71,
        ':', 40,
        '<', 79,
        '=', 75,
        '>', 80,
        ']', 6,
        'a', 20,
        'b', 25,
        'f', 18,
        'i', 21,
        'm', 11,
        'o', 26,
        's', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == 'm') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 3:
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == ']') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == ')') ADVANCE(73);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(76);
      END_STATE();
    case 9:
      if (lookahead == '[') ADVANCE(74);
      END_STATE();
    case 10:
      if (lookahead == '[') ADVANCE(72);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(66);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(1);
      END_STATE();
    case 17:
      if (lookahead == 'h') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(5);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead == 'x') ADVANCE(4);
      END_STATE();
    case 32:
      if (eof) ADVANCE(36);
      ADVANCE_MAP(
        '!', 8,
        '$', 37,
        '(', 44,
        '*', 70,
        '+', 68,
        ',', 41,
        '-', 69,
        '/', 71,
        ':', 40,
        '<', 79,
        '=', 75,
        '>', 80,
        'a', 57,
        'f', 56,
        'm', 51,
        'o', 60,
        's', 61,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 33:
      if (eof) ADVANCE(36);
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == 'o') ADVANCE(60);
      if (lookahead == 's') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 34:
      if (eof) ADVANCE(36);
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == 's') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 35:
      if (eof) ADVANCE(36);
      if (lookahead == '$') ADVANCE(37);
      if (lookahead == '(') ADVANCE(44);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 's') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_single_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_find);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_find);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_suchthat);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_bool_domain);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ' ') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '(') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead == 'i') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_or);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_and);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_min_LPAREN_LBRACK);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RBRACK_RPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_max_LPAREN_LBRACK);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(77);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(78);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 32},
  [5] = {.lex_state = 32},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 32},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 34},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 32},
  [21] = {.lex_state = 32},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 32},
  [24] = {.lex_state = 32},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 32},
  [45] = {.lex_state = 32},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 32},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 33},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 33},
  [58] = {.lex_state = 33},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 33},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 34},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 35},
  [67] = {.lex_state = 34},
  [68] = {.lex_state = 35},
  [69] = {.lex_state = 35},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 35},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 35},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 35},
  [78] = {.lex_state = 35},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 3},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 35},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 3},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_single_line_comment] = ACTIONS(3),
    [anon_sym_find] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_suchthat] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_bool_domain] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_min_LPAREN_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RPAREN] = ACTIONS(1),
    [anon_sym_max_LPAREN_LBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(113),
    [sym_find_statement_list] = STATE(71),
    [sym_constraint] = STATE(71),
    [aux_sym_program_repeat1] = STATE(71),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_single_line_comment] = ACTIONS(3),
    [anon_sym_find] = ACTIONS(7),
    [anon_sym_suchthat] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(13), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 16,
      ts_builtin_sym_end,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [30] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(5), 1,
      aux_sym_term_repeat1,
    ACTIONS(19), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(17), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(15), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [64] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(4), 1,
      aux_sym_term_repeat1,
    ACTIONS(25), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(23), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [98] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(4), 1,
      aux_sym_term_repeat1,
    ACTIONS(19), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(30), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(28), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [132] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(34), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(32), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [161] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(38), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(36), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [190] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(42), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(40), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [219] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(46), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [248] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(50), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [277] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(54), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(52), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [306] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(58), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(56), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [335] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(23), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 15,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [364] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(16), 1,
      aux_sym_addition_repeat1,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(62), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(60), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [396] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(14), 1,
      aux_sym_addition_repeat1,
    ACTIONS(64), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(68), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(66), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [428] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(16), 1,
      aux_sym_addition_repeat1,
    ACTIONS(74), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(72), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [460] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(20), 1,
      aux_sym_comparison_repeat1,
    STATE(50), 1,
      sym_comp_op,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(79), 4,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(81), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [495] = 16,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(87), 1,
      anon_sym_find,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(17), 1,
      sym_addition,
    STATE(22), 1,
      aux_sym_constraint_repeat1,
    STATE(45), 1,
      sym_comparison,
    STATE(58), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [548] = 16,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    ACTIONS(101), 1,
      anon_sym_find,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(17), 1,
      sym_addition,
    STATE(18), 1,
      aux_sym_constraint_repeat1,
    STATE(45), 1,
      sym_comparison,
    STATE(58), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(99), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [601] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(23), 1,
      aux_sym_comparison_repeat1,
    STATE(50), 1,
      sym_comp_op,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(81), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(105), 4,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(103), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [636] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(72), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 13,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [663] = 16,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(109), 1,
      anon_sym_find,
    ACTIONS(111), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(120), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(123), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(17), 1,
      sym_addition,
    STATE(22), 1,
      aux_sym_constraint_repeat1,
    STATE(45), 1,
      sym_comparison,
    STATE(58), 1,
      sym_conjunction,
    STATE(64), 1,
      sym_expression,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [716] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(23), 1,
      aux_sym_comparison_repeat1,
    STATE(50), 1,
      sym_comp_op,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(128), 4,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(130), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(126), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [751] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(128), 6,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(126), 11,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_integer,
  [776] = 13,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(43), 1,
      sym_term,
    STATE(56), 1,
      sym_addition,
    STATE(84), 1,
      sym_comparison,
    STATE(94), 1,
      sym_conjunction,
    STATE(118), 1,
      sym_expression,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [819] = 13,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(43), 1,
      sym_term,
    STATE(56), 1,
      sym_addition,
    STATE(84), 1,
      sym_comparison,
    STATE(94), 1,
      sym_conjunction,
    STATE(116), 1,
      sym_expression,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [862] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(31), 1,
      aux_sym_term_repeat1,
    ACTIONS(30), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(28), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [888] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(27), 1,
      aux_sym_term_repeat1,
    ACTIONS(17), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(146), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(15), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [914] = 12,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(17), 1,
      sym_addition,
    STATE(45), 1,
      sym_comparison,
    STATE(61), 1,
      sym_conjunction,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [954] = 12,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(43), 1,
      sym_term,
    STATE(56), 1,
      sym_addition,
    STATE(84), 1,
      sym_comparison,
    STATE(110), 1,
      sym_conjunction,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [994] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(31), 1,
      aux_sym_term_repeat1,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(148), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(21), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1020] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(34), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(32), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1041] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(38), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(36), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(42), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(40), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1083] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(13), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(11), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1104] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(46), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(44), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1125] = 11,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(43), 1,
      sym_term,
    STATE(56), 1,
      sym_addition,
    STATE(98), 1,
      sym_comparison,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1162] = 11,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(17), 1,
      sym_addition,
    STATE(55), 1,
      sym_comparison,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1199] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(58), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(56), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1220] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(50), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(48), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1241] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(54), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(52), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1262] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(23), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(21), 11,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1283] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(47), 1,
      aux_sym_addition_repeat1,
    ACTIONS(68), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(151), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(66), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1307] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(157), 1,
      anon_sym_and,
    STATE(44), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(155), 3,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1331] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(164), 1,
      anon_sym_and,
    STATE(48), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(162), 3,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1355] = 10,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(43), 1,
      sym_term,
    STATE(65), 1,
      sym_addition,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1389] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(49), 1,
      aux_sym_addition_repeat1,
    ACTIONS(62), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(151), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(60), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1413] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(164), 1,
      anon_sym_and,
    STATE(44), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(168), 3,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
    ACTIONS(166), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1437] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(49), 1,
      aux_sym_addition_repeat1,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(170), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(70), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1461] = 10,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(15), 1,
      sym_term,
    STATE(24), 1,
      sym_addition,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1495] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(46), 1,
      sym_comp_op,
    STATE(51), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(133), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(126), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(130), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1520] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(72), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(70), 9,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1539] = 9,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(3), 1,
      sym_factor,
    STATE(21), 1,
      sym_term,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1570] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(177), 1,
      anon_sym_or,
    STATE(54), 1,
      aux_sym_expression_repeat1,
    ACTIONS(175), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1593] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(155), 4,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(153), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1612] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(46), 1,
      sym_comp_op,
    STATE(59), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(77), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(81), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1637] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(184), 1,
      anon_sym_or,
    STATE(54), 1,
      aux_sym_expression_repeat1,
    ACTIONS(182), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(180), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1660] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(184), 1,
      anon_sym_or,
    STATE(57), 1,
      aux_sym_expression_repeat1,
    ACTIONS(188), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(186), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1683] = 6,
    ACTIONS(3), 1,
      sym_single_line_comment,
    STATE(46), 1,
      sym_comp_op,
    STATE(51), 1,
      aux_sym_comparison_repeat1,
    ACTIONS(83), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(103), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
    ACTIONS(81), 4,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1708] = 9,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(28), 1,
      sym_factor,
    STATE(52), 1,
      sym_term,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1739] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(175), 3,
      anon_sym_find,
      sym_identifier,
      anon_sym_or,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1757] = 8,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(136), 1,
      anon_sym_LPAREN,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(142), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(144), 1,
      sym_integer,
    STATE(42), 1,
      sym_factor,
    STATE(32), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1785] = 8,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(93), 1,
      anon_sym_min_LPAREN_LBRACK,
    ACTIONS(95), 1,
      anon_sym_max_LPAREN_LBRACK,
    ACTIONS(97), 1,
      sym_integer,
    STATE(13), 1,
      sym_factor,
    STATE(6), 4,
      sym_variable,
      sym_min,
      sym_max,
      sym_constant,
  [1813] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(192), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(190), 6,
      ts_builtin_sym_end,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1832] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(128), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(126), 7,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1849] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(198), 1,
      anon_sym_find,
    ACTIONS(200), 1,
      sym_identifier,
    STATE(104), 1,
      sym_variable,
    STATE(117), 1,
      sym_variable_list,
    ACTIONS(196), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(66), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [1873] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(109), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      anon_sym_suchthat,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [1889] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(205), 1,
      anon_sym_find,
    STATE(104), 1,
      sym_variable,
    STATE(117), 1,
      sym_variable_list,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(69), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [1913] = 7,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(91), 1,
      sym_identifier,
    ACTIONS(209), 1,
      anon_sym_find,
    STATE(104), 1,
      sym_variable,
    STATE(117), 1,
      sym_variable_list,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    STATE(66), 2,
      sym_find_statement,
      aux_sym_find_statement_list_repeat1,
  [1937] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(211), 1,
      anon_sym_DOT_DOT,
    ACTIONS(213), 1,
      sym_integer,
    STATE(119), 1,
      sym_range_list,
    STATE(100), 3,
      sym_lower_bound_range,
      sym_upper_bound_range,
      sym_closed_range,
  [1955] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(7), 1,
      anon_sym_find,
    ACTIONS(9), 1,
      anon_sym_suchthat,
    ACTIONS(215), 1,
      ts_builtin_sym_end,
    STATE(73), 3,
      sym_find_statement_list,
      sym_constraint,
      aux_sym_program_repeat1,
  [1973] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(221), 1,
      anon_sym_LPAREN,
    ACTIONS(219), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(217), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [1989] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 1,
      anon_sym_find,
    ACTIONS(228), 1,
      anon_sym_suchthat,
    STATE(73), 3,
      sym_find_statement_list,
      sym_constraint,
      aux_sym_program_repeat1,
  [2007] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(233), 1,
      sym_identifier,
    ACTIONS(231), 4,
      anon_sym_LPAREN,
      anon_sym_min_LPAREN_LBRACK,
      anon_sym_max_LPAREN_LBRACK,
      sym_integer,
  [2020] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(237), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(235), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [2033] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(211), 1,
      anon_sym_DOT_DOT,
    ACTIONS(239), 1,
      sym_integer,
    STATE(107), 3,
      sym_lower_bound_range,
      sym_upper_bound_range,
      sym_closed_range,
  [2048] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(245), 1,
      anon_sym_COMMA,
    ACTIONS(241), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(243), 2,
      anon_sym_find,
      sym_identifier,
  [2063] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(249), 2,
      anon_sym_find,
      sym_identifier,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_suchthat,
  [2076] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(253), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(80), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2092] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(255), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2108] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2124] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(259), 1,
      anon_sym_int,
    ACTIONS(261), 1,
      sym_bool_domain,
    STATE(75), 1,
      sym_int_domain,
    STATE(77), 1,
      sym_domain,
  [2140] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(263), 1,
      anon_sym_and,
    STATE(87), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(166), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2154] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(263), 1,
      anon_sym_and,
    STATE(83), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2168] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(265), 1,
      sym_identifier,
    ACTIONS(268), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2184] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(270), 2,
      ts_builtin_sym_end,
      anon_sym_suchthat,
    ACTIONS(272), 2,
      anon_sym_find,
      sym_identifier,
  [2196] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(274), 1,
      anon_sym_and,
    STATE(87), 1,
      aux_sym_conjunction_repeat1,
    ACTIONS(153), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2210] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      anon_sym_DOT_DOT,
    STATE(101), 1,
      aux_sym_range_list_repeat1,
  [2226] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(283), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(81), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2242] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(285), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(92), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2258] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(287), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(93), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2274] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(289), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2290] = 5,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    ACTIONS(291), 1,
      anon_sym_RBRACK_RPAREN,
    STATE(85), 1,
      aux_sym_min_repeat1,
    STATE(115), 1,
      sym_variable,
  [2306] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_or,
    STATE(105), 1,
      aux_sym_expression_repeat1,
  [2319] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(281), 1,
      anon_sym_DOT_DOT,
    ACTIONS(295), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2330] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    ACTIONS(297), 1,
      anon_sym_COMMA,
    STATE(96), 1,
      aux_sym_range_list_repeat1,
  [2343] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    ACTIONS(300), 1,
      anon_sym_or,
    STATE(97), 1,
      aux_sym_expression_repeat1,
  [2356] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(153), 3,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_and,
  [2365] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(303), 1,
      anon_sym_COLON,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    STATE(102), 1,
      aux_sym_variable_list_repeat1,
  [2378] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    STATE(101), 1,
      aux_sym_range_list_repeat1,
  [2391] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_range_list_repeat1,
  [2404] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(309), 1,
      anon_sym_COLON,
    ACTIONS(311), 1,
      anon_sym_COMMA,
    STATE(102), 1,
      aux_sym_variable_list_repeat1,
  [2417] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(316), 1,
      sym_integer,
    ACTIONS(314), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2428] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(305), 1,
      anon_sym_COMMA,
    ACTIONS(318), 1,
      anon_sym_COLON,
    STATE(99), 1,
      aux_sym_variable_list_repeat1,
  [2441] = 4,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_or,
    STATE(97), 1,
      aux_sym_expression_repeat1,
  [2454] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(320), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2462] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(295), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2470] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(268), 2,
      sym_identifier,
      anon_sym_RBRACK_RPAREN,
  [2478] = 3,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(112), 1,
      sym_variable,
  [2488] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(173), 2,
      anon_sym_RPAREN,
      anon_sym_or,
  [2496] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(322), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2504] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(309), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2512] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [2519] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(326), 1,
      sym_integer,
  [2526] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(328), 1,
      anon_sym_COMMA,
  [2533] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(330), 1,
      anon_sym_RPAREN,
  [2540] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(332), 1,
      anon_sym_COLON,
  [2547] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
  [2554] = 2,
    ACTIONS(3), 1,
      sym_single_line_comment,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 98,
  [SMALL_STATE(6)] = 132,
  [SMALL_STATE(7)] = 161,
  [SMALL_STATE(8)] = 190,
  [SMALL_STATE(9)] = 219,
  [SMALL_STATE(10)] = 248,
  [SMALL_STATE(11)] = 277,
  [SMALL_STATE(12)] = 306,
  [SMALL_STATE(13)] = 335,
  [SMALL_STATE(14)] = 364,
  [SMALL_STATE(15)] = 396,
  [SMALL_STATE(16)] = 428,
  [SMALL_STATE(17)] = 460,
  [SMALL_STATE(18)] = 495,
  [SMALL_STATE(19)] = 548,
  [SMALL_STATE(20)] = 601,
  [SMALL_STATE(21)] = 636,
  [SMALL_STATE(22)] = 663,
  [SMALL_STATE(23)] = 716,
  [SMALL_STATE(24)] = 751,
  [SMALL_STATE(25)] = 776,
  [SMALL_STATE(26)] = 819,
  [SMALL_STATE(27)] = 862,
  [SMALL_STATE(28)] = 888,
  [SMALL_STATE(29)] = 914,
  [SMALL_STATE(30)] = 954,
  [SMALL_STATE(31)] = 994,
  [SMALL_STATE(32)] = 1020,
  [SMALL_STATE(33)] = 1041,
  [SMALL_STATE(34)] = 1062,
  [SMALL_STATE(35)] = 1083,
  [SMALL_STATE(36)] = 1104,
  [SMALL_STATE(37)] = 1125,
  [SMALL_STATE(38)] = 1162,
  [SMALL_STATE(39)] = 1199,
  [SMALL_STATE(40)] = 1220,
  [SMALL_STATE(41)] = 1241,
  [SMALL_STATE(42)] = 1262,
  [SMALL_STATE(43)] = 1283,
  [SMALL_STATE(44)] = 1307,
  [SMALL_STATE(45)] = 1331,
  [SMALL_STATE(46)] = 1355,
  [SMALL_STATE(47)] = 1389,
  [SMALL_STATE(48)] = 1413,
  [SMALL_STATE(49)] = 1437,
  [SMALL_STATE(50)] = 1461,
  [SMALL_STATE(51)] = 1495,
  [SMALL_STATE(52)] = 1520,
  [SMALL_STATE(53)] = 1539,
  [SMALL_STATE(54)] = 1570,
  [SMALL_STATE(55)] = 1593,
  [SMALL_STATE(56)] = 1612,
  [SMALL_STATE(57)] = 1637,
  [SMALL_STATE(58)] = 1660,
  [SMALL_STATE(59)] = 1683,
  [SMALL_STATE(60)] = 1708,
  [SMALL_STATE(61)] = 1739,
  [SMALL_STATE(62)] = 1757,
  [SMALL_STATE(63)] = 1785,
  [SMALL_STATE(64)] = 1813,
  [SMALL_STATE(65)] = 1832,
  [SMALL_STATE(66)] = 1849,
  [SMALL_STATE(67)] = 1873,
  [SMALL_STATE(68)] = 1889,
  [SMALL_STATE(69)] = 1913,
  [SMALL_STATE(70)] = 1937,
  [SMALL_STATE(71)] = 1955,
  [SMALL_STATE(72)] = 1973,
  [SMALL_STATE(73)] = 1989,
  [SMALL_STATE(74)] = 2007,
  [SMALL_STATE(75)] = 2020,
  [SMALL_STATE(76)] = 2033,
  [SMALL_STATE(77)] = 2048,
  [SMALL_STATE(78)] = 2063,
  [SMALL_STATE(79)] = 2076,
  [SMALL_STATE(80)] = 2092,
  [SMALL_STATE(81)] = 2108,
  [SMALL_STATE(82)] = 2124,
  [SMALL_STATE(83)] = 2140,
  [SMALL_STATE(84)] = 2154,
  [SMALL_STATE(85)] = 2168,
  [SMALL_STATE(86)] = 2184,
  [SMALL_STATE(87)] = 2196,
  [SMALL_STATE(88)] = 2210,
  [SMALL_STATE(89)] = 2226,
  [SMALL_STATE(90)] = 2242,
  [SMALL_STATE(91)] = 2258,
  [SMALL_STATE(92)] = 2274,
  [SMALL_STATE(93)] = 2290,
  [SMALL_STATE(94)] = 2306,
  [SMALL_STATE(95)] = 2319,
  [SMALL_STATE(96)] = 2330,
  [SMALL_STATE(97)] = 2343,
  [SMALL_STATE(98)] = 2356,
  [SMALL_STATE(99)] = 2365,
  [SMALL_STATE(100)] = 2378,
  [SMALL_STATE(101)] = 2391,
  [SMALL_STATE(102)] = 2404,
  [SMALL_STATE(103)] = 2417,
  [SMALL_STATE(104)] = 2428,
  [SMALL_STATE(105)] = 2441,
  [SMALL_STATE(106)] = 2454,
  [SMALL_STATE(107)] = 2462,
  [SMALL_STATE(108)] = 2470,
  [SMALL_STATE(109)] = 2478,
  [SMALL_STATE(110)] = 2488,
  [SMALL_STATE(111)] = 2496,
  [SMALL_STATE(112)] = 2504,
  [SMALL_STATE(113)] = 2512,
  [SMALL_STATE(114)] = 2519,
  [SMALL_STATE(115)] = 2526,
  [SMALL_STATE(116)] = 2533,
  [SMALL_STATE(117)] = 2540,
  [SMALL_STATE(118)] = 2547,
  [SMALL_STATE(119)] = 2554,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 2, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min, 2, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_min, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constant, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constant, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_max, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_max, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_max, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_factor, 3, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_factor, 3, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_min, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_min, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constraint, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constraint, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comparison, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comparison, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [114] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comparison_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_term_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conjunction, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conjunction, 2, 0, 0),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_addition_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constraint_repeat1, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_constraint_repeat1, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_find_statement_list_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement_list, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement_list, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement_list, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement_list, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_domain, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_domain, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comp_op, 1, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_domain, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_domain, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement, 3, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_int_domain, 4, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_int_domain, 4, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_min_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_min_repeat1, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_find_statement, 4, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_find_statement, 4, 0, 0),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_conjunction_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_list, 1, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_range_list_repeat1, 2, 0, 0),
  [297] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_range_list_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [300] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 2, 0, 0),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_list, 2, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0),
  [311] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_list_repeat1, 2, 0, 0), SHIFT_REPEAT(109),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lower_bound_range, 2, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_list, 1, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_closed_range, 3, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_upper_bound_range, 2, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_essence(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
