use std::fmt::Display;

use serde::{Deserialize, Serialize};

/// A reference to an object stored in the [`SymbolTable`].
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    /// A name given in the input model.
    UserName(String),
    /// A name generated by Conjure-Oxide.
    MachineName(i32),

    /// A representation of another symbol.
    RepresentationOf(
        /// The source variable
        Box<Name>,
        /// The representation rule used
        String,
        /// Additional, rule dependent, information
        String,
    ),

    HasRepresentation(
        Box<Name>,
        /// representations chosen
        Vec<String>,
    ),
}

uniplate::derive_unplateable!(Name);

impl Display for Name {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Name::UserName(s) => write!(f, "{}", s),
            Name::MachineName(i) => write!(f, "__{}", i),
            Name::RepresentationOf(name, rule_string, suffix) => {
                write!(f, "{name}#{rule_string}_{suffix}")
            }
            Name::HasRepresentation(name, items) => {
                // TODO: what is the correct syntax for nested reprs?
                write!(f, "{name}#{}", items.join("#"))
            }
        }
    }
}

impl From<String> for Name {
    fn from(s: String) -> Self {
        Name::UserName(s)
    }
}

impl From<&str> for Name {
    fn from(s: &str) -> Self {
        Name::UserName(s.to_string())
    }
}

impl From<i32> for Name {
    fn from(i: i32) -> Self {
        Name::MachineName(i)
    }
}
