name: 'Coverage Report'
run-name: 'Coverage Report for ${{ github.ref }}'
on:
  push:
  pull_request:
  workflow_dispatch:

# see https://github.com/JamesIves/github-pages-deploy-action/tree/dev
permissions:
  contents: write

jobs:
  coverage-pr:
    # only do coverage for ready PRs
    if: ${{ github.event != 'pull_request' || ( github.event == 'pull_request' && (! github.event.pull_request.draft)) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get submodule hashes for cache invalidation
        id: cache-hashes
        run: |
          echo "shas=$(git rev-parse HEAD:solvers/minion/vendor)$(git rev-parse HEAD:solvers/chuffed/vendor)" >> "$GITHUB_OUTPUT"

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/            
            solvers/minion/vendor
            solvers/chuffed/vendor
          key: nightly-${{ runner.os }}-solvers-${{ steps.cache-hashes-cache.outputs.shas }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: nightly-${{ runner.os }}-solvers-${{ steps.cache-hashes-cache.outputs.shas }}-cargo-

      - name: Install rust nightly
        working-directory: ./solvers/minion
        run: rustup update nightly && rustup default nightly
      
      - name: Generate coverage reports
        working-directory: .
        run: |
          ./etc/scripts/gen_coverage_all.sh

      - name: Move all html to correct folders for deployment
        run: |
          mkdir -p deploy/conjure-oxide deploy/minion deploy/chuffed
          cp -r coverage/html/* deploy/conjure-oxide
          cp -r solvers/minion/coverage/html/* deploy/minion
          cp -r solvers/chuffed/coverage/html/* deploy/chuffed

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./deploy
          target-folder: "coverage/${{ github.sha }}"
          branch: gh-pages
          commit-message: >
            Actions: Code Coverage for ${{ github.sha }}

            ${{ github.ref }}
