name: "Documentation (Generate)"

on:
  push:
    branches:
      - main # run for pushes to the main branch
  workflow_dispatch:

env:
  rust_release: nightly
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"


jobs:
  coverage:
    name: "Generate Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Get Sha
        id: sha
        run: |
          echo -e "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          echo -e "sha=${{ github.sha }}"


      - name: Install rust ${{ env.rust_release }}
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}
      
      - name: Generate documentation
        working-directory: .
        run: |
          ./tools/gen_docs.sh
          
      - name: Move all html to correct folders for deployment
        run: |
          mkdir deploy
          cp -r target/doc/* deploy

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: docs-${{github.sha}}
          path: deploy/**
