# see: https://github.com/marketplace/actions/rust-rustfmt-check

name: rustfmt

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: rust-rustfmt-check
        uses: mbrobbel/rustfmt-check@0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review
