name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is marked as stale because it has been inactive for 90 days. If there is no new activity it will be automatically closed in 5 days. You can also mark is as planned to avoid this check.'
          days-before-issue-stale: 90
          days-before-issue-close: 5
          exempt-issue-labels: "planned,goodfirstissue"
          stale-pr-message: 'The pull request is marked as stale because it has been inactive for 30 days. If there is no new activity it will be automatically closed in 5 days.'
          stale-pr-label: stale
          days-before-pr-stale: 30
          days-before-pr-close: 5
