name: "Builds without any warnings"

on:
  push:
    branches:
      - main # run for pushes to the main branch. other branches need to create a PR if they want testing.
    paths:
      - conjure_oxide/**
      - solvers/**
      - crates/**
      - Cargo.*
      - .github/workflows/warnings.yml
  pull_request:
    paths:
      - conjure_oxide/**
      - solvers/**
      - crates/**
      - Cargo.*
      - .github/workflows/warnings.yml
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_VERSION: 4

jobs:
  build-and-test:
    name: "Build and Test"
    timeout-minutes: 10
    strategy:
      # run all combinations of the matrix even if one combination fails.
      fail-fast: false
      matrix:
        rust_release:
          - stable
        conjure_version:
          - 2.5.1
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            release_suffix: linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}

      - run: RUSTFLAGS="-D warnings" cargo build -vv --workspace

  examples:
    name: "Build Examples"
    timeout-minutes: 10
    strategy:
      # run all combinations of the matrix even if one combination fails.
      fail-fast: false
      matrix:
        rust_release:
          - stable
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - run: rustup update ${{ matrix.rust_release }} && rustup default ${{ matrix.rust_release }}

      - run: RUSTFLAGS="-D warnings" cargo build -vv --workspace --examples
